# Generated by Django 4.1.6 on 2023-02-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchase_mybag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='registrated_at',
            new_name='registered_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='storeowner',
            old_name='registrated_at',
            new_name='registered_at',
        ),
    ]
